################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################

include(FindPkgConfig)
PKG_CHECK_MODULES(PC_MALAMUTE "libmlm")
IF (NOT PC_MALAMUTE_FOUND)
    PKG_CHECK_MODULES(PC_MALAMUTE "mlm")
ENDIF (NOT PC_MALAMUTE_FOUND)

# some libraries install the headers is a subdirectory of the include dir
# returned by pkg-config, so use a wildcard match to improve chances of finding
# headers and SOs.
find_path(
    MALAMUTE_INCLUDE_DIRS
    NAMES mlm.h
    HINTS ${PC_MALAMUTE_INCLUDE_DIRS} ${PC_MALAMUTE_INCLUDE_DIRS}/*
)

find_library(
    MALAMUTE_LIBRARIES
    NAMES mlm
    HINTS ${PC_MALAMUTE_LIBRARY_DIRS} ${PC_MALAMUTE_LIBRARY_DIRS}/*
)

IF (NOT MALAMUTE_INCLUDE_DIRS STREQUAL MALAMUTE_INCLUDE_DIRS-NOTFOUND AND NOT MALAMUTE_LIBRARIES STREQUAL MALAMUTE_LIBRARIES-NOTFOUND)
    include(FindPackageHandleStandardArgs)
    FIND_PACKAGE_HANDLE_STANDARD_ARGS(MALAMUTE DEFAULT_MSG MALAMUTE_LIBRARIES MALAMUTE_INCLUDE_DIRS)
    mark_as_advanced(MALAMUTE_LIBRARIES MALAMUTE_INCLUDE_DIRS)
ENDIF (NOT MALAMUTE_INCLUDE_DIRS STREQUAL MALAMUTE_INCLUDE_DIRS-NOTFOUND AND NOT MALAMUTE_LIBRARIES STREQUAL MALAMUTE_LIBRARIES-NOTFOUND)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
