/*  =========================================================================
    alice - ALICE wrapper

    Copyright (c) etc.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef alice_library_H_INCLUDED
#define alice_library_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <malamute.h>

//  ALICE version macros for compile-time API detection

#define ALICE_VERSION_MAJOR 0
#define ALICE_VERSION_MINOR 0
#define ALICE_VERSION_PATCH 0

#define ALICE_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ALICE_VERSION \
    ALICE_MAKE_VERSION(ALICE_VERSION_MAJOR, ALICE_VERSION_MINOR, ALICE_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBALICE_STATIC
#       define ALICE_EXPORT
#   elif defined LIBALICE_EXPORTS
#       define ALICE_EXPORT __declspec(dllexport)
#   else
#       define ALICE_EXPORT __declspec(dllimport)
#   endif
#else
#   define ALICE_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _alice_class_t alice_class_t;
#define ALICE_CLASS_T_DEFINED


//  Public API classes
#include "alice_class.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
