/*  =========================================================================
    alice_classes - private header file

    Copyright (c) etc.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef ALICE_CLASSES_H_INCLUDED
#define ALICE_CLASSES_H_INCLUDED

//  External API
#include "../include/alice.h"

//  Internal API

#endif
